ALTER TABLE post
    ADD COLUMN IF NOT EXISTS deactivation_source VARCHAR(10) NULL COMMENT 'CREATOR/ADMIN',
    ADD COLUMN IF NOT EXISTS deactivation_reason VARCHAR(500) NULL,
    ADD COLUMN IF NOT EXISTS deactivated_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS deactivation_time DATETIME NULL;

ALTER TABLE post_comment
    ADD COLUMN IF NOT EXISTS deactivation_source VARCHAR(10) NULL COMMENT 'CREATOR/ADMIN',
    ADD COLUMN IF NOT EXISTS deactivation_reason VARCHAR(500) NULL,
    ADD COLUMN IF NOT EXISTS deactivated_by BIGINT UNSIGNED NULL,
    ADD COLUMN IF NOT EXISTS deactivation_time DATETIME NULL;
